language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

before_script: composer update --prefer-dist --no-interaction

script: php vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
